//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelWizard.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelWizard.Resources.Languages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Action_Apply {
            get {
                return ResourceManager.GetString("Action_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Action_Back {
            get {
                return ResourceManager.GetString("Action_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Action_Browse {
            get {
                return ResourceManager.GetString("Action_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Friend Code.
        /// </summary>
        public static string Action_CopyFriendCode {
            get {
                return ResourceManager.GetString("Action_CopyFriendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        public static string Action_DisableAll {
            get {
                return ResourceManager.GetString("Action_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do manually.
        /// </summary>
        public static string Action_DoManually {
            get {
                return ResourceManager.GetString("Action_DoManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Install.
        /// </summary>
        public static string Action_DownloadAndInstall {
            get {
                return ResourceManager.GetString("Action_DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Action_Duplicate {
            get {
                return ResourceManager.GetString("Action_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        public static string Action_EnableAll {
            get {
                return ResourceManager.GetString("Action_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Action_Export {
            get {
                return ResourceManager.GetString("Action_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Action_Favorite {
            get {
                return ResourceManager.GetString("Action_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamebanana page.
        /// </summary>
        public static string Action_GamebananaPage {
            get {
                return ResourceManager.GetString("Action_GamebananaPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Action_Import {
            get {
                return ResourceManager.GetString("Action_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Action_Install {
            get {
                return ResourceManager.GetString("Action_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        public static string Action_Keep {
            get {
                return ResourceManager.GetString("Action_Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Dolphin.
        /// </summary>
        public static string Action_LaunchDolphin {
            get {
                return ResourceManager.GetString("Action_LaunchDolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to us!.
        /// </summary>
        public static string Action_Link_Discord {
            get {
                return ResourceManager.GetString("Action_Link_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string Action_Link_Github {
            get {
                return ResourceManager.GetString("Action_Link_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us!.
        /// </summary>
        public static string Action_Link_Support {
            get {
                return ResourceManager.GetString("Action_Link_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Later.
        /// </summary>
        public static string Action_MaybeLater {
            get {
                return ResourceManager.GetString("Action_MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Action_No {
            get {
                return ResourceManager.GetString("Action_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Action_Ok {
            get {
                return ResourceManager.GetString("Action_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Action_OpenFolder {
            get {
                return ResourceManager.GetString("Action_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Action_Play {
            get {
                return ResourceManager.GetString("Action_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string Action_PlayOffline {
            get {
                return ResourceManager.GetString("Action_PlayOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        public static string Action_Randomize {
            get {
                return ResourceManager.GetString("Action_Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Action_Rename {
            get {
                return ResourceManager.GetString("Action_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Action_Report {
            get {
                return ResourceManager.GetString("Action_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Action_Revert {
            get {
                return ResourceManager.GetString("Action_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mii to &quot;My Miis&quot;.
        /// </summary>
        public static string Action_SaveExternalMii {
            get {
                return ResourceManager.GetString("Action_SaveExternalMii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        public static string Action_Unfavorite {
            get {
                return ResourceManager.GetString("Action_Unfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Install.
        /// </summary>
        public static string Action_UnInstall {
            get {
                return ResourceManager.GetString("Action_UnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mii.
        /// </summary>
        public static string Action_ViewMii {
            get {
                return ResourceManager.GetString("Action_ViewMii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mod.
        /// </summary>
        public static string Action_ViewMod {
            get {
                return ResourceManager.GetString("Action_ViewMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Room.
        /// </summary>
        public static string Action_ViewRoom {
            get {
                return ResourceManager.GetString("Action_ViewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Action_Yes {
            get {
                return ResourceManager.GetString("Action_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average VR.
        /// </summary>
        public static string Attribute_AverageRoomVr {
            get {
                return ResourceManager.GetString("Attribute_AverageRoomVr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR.
        /// </summary>
        public static string Attribute_BrAbbreviation {
            get {
                return ResourceManager.GetString("Attribute_BrAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Rating.
        /// </summary>
        public static string Attribute_BrFull {
            get {
                return ResourceManager.GetString("Attribute_BrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Attribute_Description {
            get {
                return ResourceManager.GetString("Attribute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Attribute_Downloads {
            get {
                return ResourceManager.GetString("Attribute_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Attribute_Enabled {
            get {
                return ResourceManager.GetString("Attribute_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Code.
        /// </summary>
        public static string Attribute_FriendCode {
            get {
                return ResourceManager.GetString("Attribute_FriendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Attribute_Gender {
            get {
                return ResourceManager.GetString("Attribute_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Attribute_Gender_Female {
            get {
                return ResourceManager.GetString("Attribute_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Attribute_Gender_Male {
            get {
                return ResourceManager.GetString("Attribute_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Attribute_Id {
            get {
                return ResourceManager.GetString("Attribute_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Attribute_Images {
            get {
                return ResourceManager.GetString("Attribute_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Online.
        /// </summary>
        public static string Attribute_IsOnline {
            get {
                return ResourceManager.GetString("Attribute_IsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Attribute_Likes {
            get {
                return ResourceManager.GetString("Attribute_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string Attribute_Losses {
            get {
                return ResourceManager.GetString("Attribute_Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Attribute_Message {
            get {
                return ResourceManager.GetString("Attribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Name.
        /// </summary>
        public static string Attribute_ModName {
            get {
                return ResourceManager.GetString("Attribute_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Attribute_Name {
            get {
                return ResourceManager.GetString("Attribute_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Attribute_PlayerCount {
            get {
                return ResourceManager.GetString("Attribute_PlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Attribute_Priority {
            get {
                return ResourceManager.GetString("Attribute_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races played.
        /// </summary>
        public static string Attribute_RacesPlayed {
            get {
                return ResourceManager.GetString("Attribute_RacesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string Attribute_SortBy {
            get {
                return ResourceManager.GetString("Attribute_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Attribute_Speed {
            get {
                return ResourceManager.GetString("Attribute_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Attribute_Status {
            get {
                return ResourceManager.GetString("Attribute_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Attribute_Status_Offline {
            get {
                return ResourceManager.GetString("Attribute_Status_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Attribute_Status_Online {
            get {
                return ResourceManager.GetString("Attribute_Status_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Online.
        /// </summary>
        public static string Attribute_TimeOnline {
            get {
                return ResourceManager.GetString("Attribute_TimeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Attribute_Title {
            get {
                return ResourceManager.GetString("Attribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total games played.
        /// </summary>
        public static string Attribute_TotalGamesPlayed {
            get {
                return ResourceManager.GetString("Attribute_TotalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total games won.
        /// </summary>
        public static string Attribute_TotalGamesWon {
            get {
                return ResourceManager.GetString("Attribute_TotalGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Attribute_Type {
            get {
                return ResourceManager.GetString("Attribute_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Attribute_Views {
            get {
                return ResourceManager.GetString("Attribute_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR.
        /// </summary>
        public static string Attribute_VrAbbreviation {
            get {
                return ResourceManager.GetString("Attribute_VrAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versus Rating.
        /// </summary>
        public static string Attribute_VrFull {
            get {
                return ResourceManager.GetString("Attribute_VrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string Attribute_Wins {
            get {
                return ResourceManager.GetString("Attribute_Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string ListTitle_Friends {
            get {
                return ResourceManager.GetString("ListTitle_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miis.
        /// </summary>
        public static string ListTitle_Miis {
            get {
                return ResourceManager.GetString("ListTitle_Miis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string ListTitle_Players {
            get {
                return ResourceManager.GetString("ListTitle_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string ListTitle_Rooms {
            get {
                return ResourceManager.GetString("ListTitle_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string PageTitle_Friends {
            get {
                return ResourceManager.GetString("PageTitle_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PageTitle_Home {
            get {
                return ResourceManager.GetString("PageTitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stuff.
        /// </summary>
        public static string PageTitle_Mods {
            get {
                return ResourceManager.GetString("PageTitle_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Miis.
        /// </summary>
        public static string PageTitle_MyMiis {
            get {
                return ResourceManager.GetString("PageTitle_MyMiis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profiles.
        /// </summary>
        public static string PageTitle_MyProfiles {
            get {
                return ResourceManager.GetString("PageTitle_MyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Details.
        /// </summary>
        public static string PageTitle_RoomDetails {
            get {
                return ResourceManager.GetString("PageTitle_RoomDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string PageTitle_Rooms {
            get {
                return ResourceManager.GetString("PageTitle_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PageTitle_Settings {
            get {
                return ResourceManager.GetString("PageTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string Region_America {
            get {
                return ResourceManager.GetString("Region_America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        public static string Region_Australia {
            get {
                return ResourceManager.GetString("Region_Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string Region_China {
            get {
                return ResourceManager.GetString("Region_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Region_Europe {
            get {
                return ResourceManager.GetString("Region_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Region_Japan {
            get {
                return ResourceManager.GetString("Region_Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea.
        /// </summary>
        public static string Region_SouthKorea {
            get {
                return ResourceManager.GetString("Region_SouthKorea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan.
        /// </summary>
        public static string Region_Taiwan {
            get {
                return ResourceManager.GetString("Region_Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Not Finished.
        /// </summary>
        public static string State_ConfigNotFinished {
            get {
                return ResourceManager.GetString("State_ConfigNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string State_Custom {
            get {
                return ResourceManager.GetString("State_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string State_Error {
            get {
                return ResourceManager.GetString("State_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files....
        /// </summary>
        public static string State_Extracting {
            get {
                return ResourceManager.GetString("State_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string State_Installed {
            get {
                return ResourceManager.GetString("State_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string State_Installing {
            get {
                return ResourceManager.GetString("State_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string State_Loading {
            get {
                return ResourceManager.GetString("State_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license.
        /// </summary>
        public static string State_NoLicense {
            get {
                return ResourceManager.GetString("State_NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        public static string State_NoName {
            get {
                return ResourceManager.GetString("State_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles.
        /// </summary>
        public static string State_NoProfiles {
            get {
                return ResourceManager.GetString("State_NoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server.
        /// </summary>
        public static string State_NoServer {
            get {
                return ResourceManager.GetString("State_NoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string State_Success {
            get {
                return ResourceManager.GetString("State_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string State_Unknown {
            get {
                return ResourceManager.GetString("State_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string State_Updating {
            get {
                return ResourceManager.GetString("State_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string State_Warning {
            get {
                return ResourceManager.GetString("State_Warning", resourceCulture);
            }
        }
    }
}
